### ISSUE TITLE
Mismatch implementation wrt equation in the paper?

### ISSUE THREAD

**Issue by Nelson-iitp** [mlyg/mixed-focal-loss#19]
In your paper "Unified Focal loss: Generalising Dice and cross entropy-based losses to handle class imbalanced medical image segmentation" in [Elviser](https://doi.org/10.1016/j.compmedimag.2021.102026), equation (20) is like :

![SS](https://user-images.githubusercontent.com/77749100/215302554-bf4ae140-5b3c-42e4-8e0b-952fad27e963.png)

But, in line [277](https://github.com/mlyg/unified-focal-loss/blob/411c9c5ce43b2ef847f0903d1b841512ad8d2eee/loss_functions.py#L277) you have multiplied cross-entrocpy of the 'common' class instead of rare class a mentioned in paper. Which one is correct?

**Comment by mlyg** [comment]
Hi Nelson,

That is a good spot, thank you for pointing it out! There is a mistake in the equation in the paper which should say log(pt,c) rather than log(pt,r). The code is correct :)
I hope that answers your question.

Best wishes,
Michael
