### ISSUE TITLE
Multiclass

### ISSUE THREAD

**Issue by c-winder** [mlyg/mixed-focal-loss#20]
Hi,

In your example use-cases, you show a multiclass example, but as far as I can tell your code only works for binary classification (forgive me if I'm wrong, I use pytorch not tf). If this is the case, could you share your implementation of using the function in the multiclass case? Guessing it would be a loop over 

Additionally, how do you use the delta parameter in the multiclass case? Should it have a different value based on how common each class is or would you choose a constant value for all classes?

Thanks

**Comment by tayden** [comment]
@c-winder, wondering what you came up with to make this work for multiclass inputs? Just looping?

**Comment by Jose-Verdu-Diaz** [comment]
> [@c-winder](https://github.com/c-winder), wondering what you came up with to make this work for multiclass inputs? Just looping?

The author provided a multiclass implementation in #8. I haven't tried it yet, but I hope it helps.
